### ISSUE TITLE
colour boxes don't stretch with long names.

### ISSUE THREAD

**Issue by ZZetho** [Halbann/LazyPainter#2]
if you put in a really long custom name the gui stretches but the colour boxes do not stretch.
![bug](https://github.com/user-attachments/assets/21d78c5d-78f4-4a0d-9c56-e50effaf0b05)

**Comment by Halbann** [comment]
This is because the positions of the boxes have to be hardcoded. Will probably have to prevent the custom name box from expanding,

**Comment by Halbann** [comment]
FIxed in 0.4.0
